### PR TITLE
small syntax error

### PR DESCRIPTION
**Pull request by regadas**

### CODE REVIEW

**Comment by axsuul** [comment]
please merge this, I am also getting this syntax error

**Comment by warmwaffles** [comment]
I too am getting this error

**Comment by axsuul** [comment]
You can use my fork in the meantime which fixes it: `git://github.com/Axsuul/citier.git`

**Comment by warmwaffles** [comment]
I'm not gonna fork it, I'll just install my gem from it until the request gets merged

**Comment by petehamilton** [comment]
Apologies for not merging this sooner

**Pull request merged**
